---
# example for listing all namespaces

- name: Playbook deploying an example application using helm packages
  hosts: all
  connection: local
  # vars:
  #   app_name: "mydemo"
  #   namespace: "demo-from-automation"
  tasks:
    - name: Create {{ namespace }} namespace
      community.okd.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create application service
      community.okd.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: "{{ app_name }}"
              service: "{{ namespace }}"
          spec:
            selector:
              app: "{{ app_name }}"
              service: "{{ namespace }}"
            ports:
            - protocol: TCP
              targetPort: 8080
              name: port-8080-tcp
              port: 8080

    - name: Create application pod
      community.okd.k8s:
        state: present
        definition:
          kind: Pod
          apiVersion: v1
          metadata:
            annotations:
              openshift.io/generated-by: startx-automation
            name: "{{ app_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: "{{ app_name }}"
              service: "{{ namespace }}"
          spec:
            containers:
              - name: application
                image: 'quay.io/startx/php:alpine3'
                resources:
                  limits:
                    cpu: 50m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                ports:
                  - containerPort: 8080
                    protocol: TCP
                command:
                  - /bin/sx-apache
                args:
                  - run