---
# example for listing all namespaces

- name: Playbook listing all namespaces against a k8s cluster
  hosts: all
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: Fetch the namespaces list
      set_fact:
        projects: "{{ lookup('k8s', api_version='v1', kind='Namespace') }}"
    
    - name: Display namespaces list
      debug:
        var: "{{ projects }}"
...
